# Generated by Django 5.2.5 on 2025-08-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
