# Generated by Django 5.2.5 on 2025-08-26 10:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_review_description_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratings',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(5)]),
        ),
    ]
