# Generated by Django 5.2.5 on 2025-08-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
