# Generated by Django 5.2.5 on 2025-08-27 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_quality_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not paid', 'Not paid'), ('shipped', 'Shipped'), ('Ready to ship', 'Ready to ship'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], default='Not paid', max_length=20),
        ),
    ]
